allowBuilds:
  esbuild: false # postinstall not necessary for functionality, see https://github.com/evanw/esbuild/issues/4085
  sharp: false
minimumReleaseAge: 10080 # 1 week
trustPolicy: no-downgrade
savePrefix: ''
autoInstallPeers: true
strictPeerDependencies: false
